services:
  db:
    image: postgres:16
    container_name: encuestas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - encuestas_pgdata:/var/lib/postgresql/data

volumes:
  encuestas_pgdata: