import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./global.scss";
import { Session, getServerSession } from "next-auth";
import SessionProvider from "@/components/session-provider/session-provider";
import { authOptions } from "@/utils/auth-options";
import { getUserByEmail } from "@/lib/api/users";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  //const user = await getUserByEmail(session?.user?.email as string);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
